// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using proyecto_entityframework;

#nullable disable

namespace proyectoentityframework.Migrations
{
    [DbContext(typeof(ProyectoContext))]
    partial class ProyectoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("proyecto_entityframework.Modelos.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c4e0d0e7-5f06-48c7-9246-11fe12f2c657"),
                            Nombre = "Pending activities",
                            Peso = 20
                        },
                        new
                        {
                            Id = new Guid("c4e0d0e7-5f06-48c7-9246-11fe12f2c602"),
                            Nombre = "Personal activities",
                            Peso = 50
                        });
                });

            modelBuilder.Entity("proyecto_entityframework.Modelos.Tarea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c4e0d0e7-5f06-48c7-9246-11fe12f2c100"),
                            CategoriaId = new Guid("c4e0d0e7-5f06-48c7-9246-11fe12f2c657"),
                            FechaCreacion = new DateTime(2023, 8, 17, 11, 1, 35, 705, DateTimeKind.Local).AddTicks(3815),
                            Prioridad = 1,
                            Titulo = "Payment of public services"
                        },
                        new
                        {
                            Id = new Guid("c4e0d0e7-5f06-48c7-9246-11fe12f2c101"),
                            CategoriaId = new Guid("c4e0d0e7-5f06-48c7-9246-11fe12f2c602"),
                            FechaCreacion = new DateTime(2023, 8, 17, 11, 1, 35, 705, DateTimeKind.Local).AddTicks(3834),
                            Prioridad = 0,
                            Titulo = "Finish watching movie"
                        });
                });

            modelBuilder.Entity("proyecto_entityframework.Modelos.Tarea", b =>
                {
                    b.HasOne("proyecto_entityframework.Modelos.Categoria", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("proyecto_entityframework.Modelos.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
